package co.ke.mkeja.onboarding.event;

public enum OnboardingEventType {
    LANDLORD_REGISTERED,
    AGENT_REGISTERED,
    PROPERTY_CREATED,
    PROPERTY_VERIFIED,
    UNIT_CREATED,
    LISTING_UPDATED,
    INVITATION_SENT,
    INVITATION_ACCEPTED,
    TENANT_ONBOARDED,
    LEASE_SIGNED,
    TENANCY_CREATED,
    TENANCY_TERMINATED,
    KYC_VERIFIED,
    KYC_REJECTED
}
