short-code=56789
transaction-type=
identifier=
pass-key=
callback-url=
consumer-key=UHhx3yy4O0oMDyppp2PZEhhEYpXRv5nRdH5NXEZi2AZSfBjg
consumer-secret=Rbxjx8f3C1MNO7TwIFBE1gV6AVWR0uKobS0eGfiasyfE70zhxaM31MxBywcJE174
auth-url=https://sandbox.safaricom.co.ke/oauth/v1/generate
payment-url=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
query-url=https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query